language: bash
services: docker
sudo: required

notifications:
  slack:
    secure: wWYsB6qt9uoHZr0hFKzue+LIudSbNsiMWl75XqidfEPorE1vQ5t7XnUcvspE2jwn0mK2TjKkunGSH7bk1w3kZ5YnWsSf6LlmCUqSK4k+o6CeZUFeVg4P5uhxxhQx/68Us3YXBoszc68UphNwvFA4RryA2SsBk1jDToYfWcm1M5UPD23UacrQDBYbfuwCvdztQNuGbY+mBEYg8h6MFG+nwKc8u9SvGE2hu+l6IsrsCR9dTYmcMpqR9lL1qCNvhFdD5GM8dOfl94ZArTajNHpo2Z+QGb0BwdtKTI8/gO9m2+9sW0bKfNE7Gudp1olE4UECGCbGXx7WgcfpylfVVOPk8y+Ya6LWahQpkJAr6dyQ2ymSPP3EIoyhfgdER8q/et3fybX54EyLHI8eiUxwNy4/kei9F5gMbmCGFgBEbG1/ruxi6/nPswYTCb0WKZV+Qiim71xwsV0e+HfFARCWc+Zh6cGx+c/9EXJEnd7OMDIN+nHV05lpm3xzdgWjO6eRPBiGo0unS/N6F+AFkqFEuPiBLhHujppN2aCM1kGkw2GNa+sXI0Jz73q9GXoALP9YhS21Sj9cQw5U0k6QA77Qjm3Vwmhd3tlejt7M5iuk90IkE1GHD6Q6swxpjUwZdr7KfiVcHoHKArb1Gskln+IQFWEYP/9GUnOjN9/WF9hBQuTqi0I=
    on_success: change

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register

script:
  - docker build -t napnap75/rpi-sickrage:latest .
  - docker images

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push napnap75/rpi-sickrage:latest
  - export CURRENTDATE=$(date +%y%m%d)
  - docker tag napnap75/rpi-sickrage:latest napnap75/rpi-sickrage:$CURRENTDATE
  - docker push napnap75/rpi-sickrage:$CURRENTDATE
